// fuzz_test.go — record-layer fuzz target for the gostls record package.
//
// Contract: FuzzReadRecord must never panic on arbitrary input. A malformed
// header or payload must return an error, not crash.
//
// Run for 5 seconds to confirm the target works:
//
//	CGO_ENABLED=0 go test ./internal/record/ -run '^$' -fuzz FuzzReadRecord -fuzztime 5s
package record_test

import (
	"bytes"
	"testing"

	"github.com/bigbes/gostls/internal/record"
)

// FuzzReadRecord feeds arbitrary bytes to record.Layer.ReadRecord via an
// in-memory reader. The corpus seed is a minimal valid TLS 1.2 application_data
// record carrying a single zero byte; further mutations are generated by the
// fuzzer engine.
//
// Contract: never panic. Every malformed input (truncated header, wrong version,
// unknown content type, oversized fragment, bad MAC) must return an error.
func FuzzReadRecord(f *testing.F) {
	// Seed: a valid TLS 1.2 application_data record with 1-byte payload 0x00.
	// Header: type=0x17 (23), version=0x0303 (TLS 1.2), length=0x0001.
	// Body: 0x00.
	f.Add([]byte{0x17, 0x03, 0x03, 0x00, 0x01, 0x00})

	// Seed: valid alert record (close_notify warning).
	f.Add([]byte{0x15, 0x03, 0x03, 0x00, 0x02, 0x01, 0x00})

	// Seed: valid handshake record (4-byte body).
	f.Add([]byte{0x16, 0x03, 0x03, 0x00, 0x04, 0xAA, 0xBB, 0xCC, 0xDD})

	// Seed: truncated header (only 3 bytes).
	f.Add([]byte{0x17, 0x03, 0x03})

	// Seed: oversized fragment claim (length > 2^14+2048).
	f.Add([]byte{0x17, 0x03, 0x03, 0xFF, 0xFF})

	// Seed: wrong version (TLS 1.0).
	f.Add([]byte{0x17, 0x03, 0x01, 0x00, 0x01, 0x00})

	// Seed: unknown content type.
	f.Add([]byte{0x42, 0x03, 0x03, 0x00, 0x01, 0x00})

	f.Fuzz(func(t *testing.T, data []byte) {
		// Never panic — errors are fine, crashes are not.
		// readOnlyRW (defined in record_test.go) wraps bytes.Reader as io.ReadWriter.
		rw := readOnlyRW{bytes.NewReader(data)}
		l := record.NewLayer(rw)
		// Ignore returned values; only check for panics.
		_, _, _ = l.ReadRecord()
	})
}
